port: 8080
name: go-web
# mysql 配置
mysql:
  host: mysql57 # docker 配置容器名称, 本地开发使用 localhost
  port: 3306
  user: root
  password: root123456 # docker 配置容mysql器密码, 本地开发使用 123456
  db: goweb
# redis 配置
redis:
  host: redis # docker 配置容器名称, 本地开发使用 localhost
  port: 6379
  password: 

