package routers

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"lirawx.cn/go-web/controllers"

	_ "lirawx.cn/go-web/docs" // docs is generated by Swag CLI, you have to import it.
)

// SetupRouter 配置路由信息
func SetupRouter() *gin.Engine {
	r := gin.Default()
	// Swagger
	url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	r.GET("/hello", controllers.HelloController)

	r.POST("/addTodo", controllers.CreateTodo)
	r.GET("/getTodoList", controllers.GetTodoList)
	return r
}
